### PR TITLE
 Add Email Verification During Sign-Up

### LINKED ISSUE #430: FEATURE: Revamp Sign-Up Page with Verification Functionality
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Objective:**  
Revise and improve the current sign-up page to add essential features for better user experience, account security, and database integrity.

### Scope of Changes

1. **Enforce Email Verification Requirement:**  
   - Introduce a mandatory email verification step before account creation. Users must click a verification link sent to their email address to complete the registration process.

2. **Username Availability Check:**  
   - Implement real-time validation to check if the chosen username is already taken. Users will be informed immediately when a username is unavailable.

3. **Email Availability Check:**  
   - Implement real-time validation to check if the entered email address is already associated with an existing account. Users will be notified immediately if the email is already registered in the database.

### Component

/signup page

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
### **Description**:
This PR introduces the functionality to verify the user's email during the sign-up process. After a successful sign-up, the user is prompted to verify their email by clicking a link sent to their email address. The link is valid for 24 hours, after which it expires. Additionally, the login backend has been updated to allow only verified users to log in.

### **Changes Made**:

1. **Email Verification After Sign-Up**:
    - **Flow**: After the user successfully signs up, an email is sent containing a verification link.
    - **Verification Link**: The link expires after 24 hours, requiring the user to verify their email within that time frame.
    - **Email Content**: The email includes a unique token that the user can use to verify their email address.
  
2. **Login Backend Updates**:
    - Updated the login endpoint to check if the user has a verified email before allowing login.
    - If the user's email is not verified, the login attempt will be rejected with a relevant message ("Please verify your email to log in").
    - Introduced a new `emailVerified` field in the user model to track email verification status.

3. **Frontend Changes**:
    - Added a prompt for users to verify their email after they sign up, with a link to resend the verification email if necessary.
    - If the user tries to log in before verifying their email, an error message will be displayed indicating that the email needs to be verified first.

### **Screenshots/GIFs**: (Optional)

https://github.com/user-attachments/assets/d64128e9-848d-4118-a17f-95aa0772a490

- Fixes #430 

## How should this be tested?

-  Go to Sign Up Page and register as new user. it will guide you through

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique as you can see this PR is already big so I will be implementing two features i.e
1) Deletion of unverified accound after 24 hours 
2) Resend verification Email Feature
in another PR. I hope you dont mind.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean update this PR

**Comment by AlfiyaSiddique** [comment]
And in the video there are multiple success alert, is that fixed?

**Comment by IkkiOcean** [comment]
> And in the video there are multiple success alert, is that fixed?

yeah that's removed. I think I uploaded the earlier video

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean GETTING THIS ERROR IN LOG AND NOT ABLE TO SIGNUP:
image
 Any idea what's the issue, I checked the env variables they look good
 Any configuration that is needed from my side?

**Pull request merged**
