### PR TITLE
Implement Feature to Delete User Account

### LINKED ISSUE #414: FEATURE: Add "Delete Account" Option in Tasty Trail Profile
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

#### Description
Add a feature that allows users to delete their account from Tasty Trail. This option will provide users with more control over their personal data and ensure compliance with data privacy standards. Upon deletion, all user data, including saved recipes, reviews, and profile information, should be removed from the system.

#### Requirements
1. **Delete Account Option**:
   - Add a "Delete Account" button in the profile settings section.
   - Include a confirmation prompt to prevent accidental deletions.
   - Display a final warning explaining that account deletion is irreversible and will result in the permanent loss of all data.

2. **Data Removal**:
   - Ensure that all user-related data is completely removed from the database upon account deletion (e.g., saved recipes, reviews, and profile information).
   - Remove any third-party integrations or authentication tokens associated with the user.

3. **Confirmation and Feedback**:
   - Provide a success message once the account is successfully deleted.
   - Optionally, redirect the user to a goodbye or feedback page to understand their reason for leaving.

### Component

/profile

### It should be implemented because

1. **User Control and Autonomy**:
   - Users today expect full control over their data, including the ability to delete their accounts when desired. This feature empowers users by giving them the freedom to manage their relationship with the app, respecting their choices.

2. **Data Privacy Compliance**:
   - Many data protection regulations (such as GDPR in Europe and CCPA in California) require platforms to provide users with an option to delete their accounts and personal data. Implementing this feature ensures that Tasty Trail complies with these standards, reducing the risk of legal issues.

3. **Building Trust and Transparency**:
   - Allowing users to delete their accounts fosters trust, showing them that Tasty Trail values transparency and respects their privacy. This can improve brand reputation and user loyalty, as users feel more confident that their data is handled responsibly.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
#### Description
This PR introduces a new feature that allows users to permanently delete their accounts. The deletion process ensures that all associated data, including recipes, feedback, and comments, is also removed from the database. A confirmation prompt has been integrated into the frontend to enhance user experience and prevent accidental deletions.

#### Changes Made
1. **Backend:**
   - Created an API endpoint to delete user accounts along with all associated data.
     - **Endpoint:** `DELETE /api/user/delete/:id`
     - This API removes:
       - User account
       - User-created recipes
       - User-submitted feedback
       - User comments
   - Updated the User Controller to handle the deletion logic effectively.

2. **Frontend:**
   - Integrated the account deletion feature into the user settings page.
   - Implemented a confirmation modal that prompts users to enter their username before proceeding with the deletion:
     - The modal notifies users that the action is irreversible.
     - The "Delete" button is disabled until the correct username is typed in.

#### How to Test
1. **API Testing:**
   - Send a DELETE request to `DELETE /api/user/delete/:id` with a valid user ID.
   - Confirm that the user and all associated data are deleted from the database.

2. **Frontend Testing:**
   - Navigate to the profile page.
   - Trigger the account deletion process.
   - Verify that the confirmation modal appears and requires the username for confirmation.
   - Ensure the "Delete" button is disabled until the correct username is entered.
   - Upon confirming, check that the user account and associated data are removed successfully.

#### Related Issues
- Closes #414 

#### Video

https://github.com/user-attachments/assets/ef134802-06b8-44ef-bbc8-853de52ac6c0

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique while working on it, I happened to know that currently backend it uploading profile image to GitHub, which isn't a good practice and jeopardices user privacy. Would you like me to raise an issue about it and solve it? I can encrypt the image and store it in database itself. It will be much faster data retrieval technique.

**Comment by AlfiyaSiddique** [comment]
>@AlfiyaSiddique while working on it, I happened to know that currently backend is uploading profile image to GitHub, which isn't a good practice and jeopardises user privacy. Would you like me to raise an issue about it and solve it? I can encrypt the image and store it in database itself. It will be much faster data retrieval technique.

@IkkiOcean will look into this once and let you know;
Also will review the PR on Friday

**Comment by AlfiyaSiddique** [comment]
>@AlfiyaSiddique while working on it, I happened to know that currently backend is uploading profile image to GitHub, which isn't a good practice and jeopardises user privacy. Would you like me to raise an issue about it and solve it? I can encrypt the image and store it in database itself. It will be much faster data retrieval technique.

@IkkiOcean checked this and the profile image is getting stored in the database only:

>const UpdateImage = async (req, res) => {
  try {
    const { id, profile} = req.body
    const update = await User.updateOne({ _id: id }, { $set: {profile: profile} }, { new: true })
    return res.status(200).json({ success: true, message: "Image Updates Successfully" })
  } catch (error) {
    console.log(error);
    res.status(404).json({ success: false, message: "Internal server error" });
  }
}

And I am aware that we are using Github for recipe image upload and not for profile image upload, so if you want you can work on to store recipe image in database instead of Github repo

**Comment by IkkiOcean** [comment]
> > @AlfiyaSiddique while working on it, I happened to know that currently backend is uploading profile image to GitHub, which isn't a good practice and jeopardises user privacy. Would you like me to raise an issue about it and solve it? I can encrypt the image and store it in database itself. It will be much faster data retrieval technique.
> 
> @IkkiOcean checked this and the profile image is getting stored in the database only:
> 
> > const UpdateImage = async (req, res) => {
> > try {
> > const { id, profile} = req.body
> > const update = await User.updateOne({ _id: id }, { $set: {profile: profile} }, { new: true })
> > return res.status(200).json({ success: true, message: "Image Updates Successfully" })
> > } catch (error) {
> > console.log(error);
> > res.status(404).json({ success: false, message: "Internal server error" });
> > }
> > }
> 
> And I am aware that we are using Github for recipe image upload and not for profile image upload, so if you want you can work on to store recipe image in database instead of Github repo

yeas. I meant the recipe image itself. I must have confused it with profile. okay I will raise the pr

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean great work on this Project! 👏🏻👏🏻👏🏻
Thanks for opening good initiatives for this project.
Your code is always clean and easy to review
Keep up the good work!🙌🏻

**Pull request merged**
