### PR TITLE
Added issues_templates

### PR DESCRIPTION
**Pull request by sadath2001**
Issue #45 
I have added the issue templates as follows
Bug
New Feature
Enhancement
config to direct to discussion

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@sadath2001 can you please add test images for this feature in the comment by creating issues on your forked repo?

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , could you please review the screenshots ive mentioned in the linked issue?

**Comment by AlfiyaSiddique** [comment]
@sadath2001 looks good

**Comment by sadath2001** [comment]
Thanks, I'll get the chat and outh feature done too probably by tonight.

**Pull request merged**
