### PR TITLE
resolved the reference error for pagination issue #102

### PR DESCRIPTION
**Pull request by sadath2001**
https://github.com/user-attachments/assets/3198c3e1-ea89-40e5-9b8c-4649c86f4ca4

Apparently a small bug

issue: #102

### CODE REVIEW

**Comment by sadath2001** [comment]
also i could see that in the original issue, this  was a level2, but here it was changed to level1. May i know the reason why?

**Comment by AlfiyaSiddique** [comment]
@sadath2001 changed the label my mistake

**Comment by AlfiyaSiddique** [comment]
@sadath2001 the output is not working on the preview.
Please confirm that the output comes in preview

**Comment by AlfiyaSiddique** [comment]
@sadath2001 can you fix this on priority, level 2 on this issue is for fixing it quickly otherwise the bug is not difficult to solve. Please check into it asap.

**Comment by AlfiyaSiddique** [comment]
Seems like it was due to some network issue. Now working fine, reviewing this PR now

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
