### PR TITLE
✨ Dark mode Toggle added ✨ (issuse #57)

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the dark mode toggle works fine for all the pages.
**Please do consider the PR , thank you!**

https://github.com/user-attachments/assets/51cd5ccb-fd8c-44c3-9d7d-3ff78d4155c3

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
can you please assign the level as well.

**Comment by T-Rahul-prabhu-38** [comment]
@AlfiyaSiddique  Can u accept PR. Thank You!

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38  Please update your branch and resolve conflicts

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 
Also, the implemented dark mode is not looking good.
These are the issues with it:
1. The button is too simple - Add something like an icon of the sun and moon for light and dark mode
2. The black color is too dark and contrast use a relatively light black color
3. When you are making the background color black please plan according so that the recipe cards and other texts do not fades in which is the case currently
Please fix these

**Comment by T-Rahul-prabhu-38** [comment]
sure, ill create a new PR.

**Comment by T-Rahul-prabhu-38** [comment]
@AlfiyaSiddique  i wanted to know to make it more unique would assign level 3 please.

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 dark-mode is not a very necessary and required feature for this site so it won't assign you level3

**Pull request closed without merging**
