### PR TITLE
[FEAT] Added Testimonial Component to Landing Page

### LINKED ISSUE #75: Testimonial section in website
Hi @AlfiyaSiddique 
I will add a testimonial section in the website or our happy costumer section which will attract more users , so pls assign me this issue under hacktober fest.

### LINKED ISSUE #334: FEATURE: Implement Carousel for User Testimonial for Tasty Trails as a Service
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

We need to implement a carousel component to display user testimonials  on the homepage. This will enhance the user experience by allowing visitors to easily browse through reviews without overwhelming them with too much information at once.

### demo video:

https://github.com/user-attachments/assets/26637401-25c2-4f2a-a769-0b6e647c897d

### Component

/frontend/src/pages/landing.jsx

### It should be implemented because

- Enhanced User Experience
A carousel provides a visually appealing way to display reviews, making it easier for users to engage with feedback without feeling overwhelmed by information.

- Highlighting Positive Feedback
A carousel can be used strategically to showcase particularly glowing reviews, building trust and credibility for the brand or product.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
## What does this PR do?

This PR adds a new `Testimonial` component to the landing page of our recipe-providing website. The component displays user reviews, enhancing the credibility of our platform by showcasing positive user experiences with our recipes.

- Closes #334 

## How should this be tested?

To verify the changes, please follow these steps:

1. **Review the Testimonial Component**:
   - Navigate to the landing page.
   - Ensure the testimonial component is displayed correctly.
   - Check that the user reviews, quotes, and star ratings are accurate.

2. **Test Responsiveness**:
   - Resize the browser window to confirm the component is responsive on different screen sizes (mobile and desktop).

3. **Navigation**:
   - Test the left and right navigation buttons to ensure they scroll through testimonials correctly.
   - Verify the current testimonial indicator is functioning.

### Screenshots

- Responsive Design:

Screenshot 2024-10-25 at 6 59 12 PM

- Video

https://github.com/user-attachments/assets/fdb3b503-bea8-48f5-be8f-b830f82f1374

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
please add level 3 tag for this.

**Comment by IkkiOcean** [comment]
to further develop this feature I want to add a "Review us" Section to write these testimonials. it will like a model form (maybe an optional option on profile page). Should I raise an issue about it?

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique please look into my PR soon

**Comment by AlfiyaSiddique** [comment]
>to further develop this feature I want to add a "Add your Testimonial" Section to write these testimonials. it will be like a model form (maybe an optional option on the profile page). Should I raise an issue about it?

@IkkiOcean  you can use feedback form data for this. It is getting implemented and will be completed in 1 or 2 days—no need for a separate form. You can get the feedbacks from database

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique okay. can you merge this and I will connect it to database when that's done in a separate pr.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean merging this issue. For the backend implementation open a separate issue. Will assign you
Thanks for the contribution

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique if there any way I could get reminded when the feedback form and its backend get ready? so that I can start working on this one

**Comment by AlfiyaSiddique** [comment]
keep an eye on #349 
Most likely it will get merged today

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique I raised the issue. please assign soon.

**Pull request merged**
