### PR TITLE
Applied pagination in both frontend and backend

### PR DESCRIPTION
**Pull request by ak3264114**
this is the detailed pr of issue #5 

- [x] added pagination in both frontend and backend
- [x] added search functionalities to search from the database
- [x] code refactor
- [x] Infinite call of api removed from landing page

image

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@ak3264114, The recipe page is crashing due to an error, Please check!

https://github.com/user-attachments/assets/56548934-6f82-4bdb-93aa-abfc57b144b0

**Comment by ak3264114** [comment]
@AlfiyaSiddique 
as i have made changes in the backend response also but only you can see the frontend preview and backend is still not deployed to my latest that's why the issue arise

**Comment by ak3264114** [comment]
here i have update the response 

image


Backend response after changes (now): 
```json
{
  "success": true,
  "recipes": [
    // array of recipes
  ],
  "pagination": {
    "totalRecipes": 100,
    "currentPage": 1,
    "totalPages": 10,
    "limit": 10
  }
}
```


Backend response before changes (previous) : 
```json
{
  "success": true,
  "recipes": [
    // array of recipes
  ],
}
```

**Comment by AlfiyaSiddique** [comment]
Okay understood! @ak3264114 
Merging this PR now!
But if we find any error after merging the PR on production will revert the changes back.

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
