### PR TITLE
added dark mode

### LINKED ISSUE #57: [feature enhancement] : Dark mode toggle
### **Is your feature request related to a problem? Please describe.**
there is no preferences in the website to toggle between dark and light mode.I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode. please assign me this task.

### PR DESCRIPTION
**Pull request by Abhi0049k**
### Add Dark Mode Support
This PR implements dark mode across the application to enhance the user experience, especially for users who prefer darker themes. The dark mode styling adapts dynamically based on the user's system preference or theme selection.

#### Key Changes:
1. **Dark Mode Styles:**
   - Background and text colors across the app now support dark mode using TailwindCSS utilities.
   - Conditional styling added to key components like the **Hero**, **Features**, **Best Dishes**, and **About** sections.
   - Improved contrast for better readability in dark mode.

2. **Hero Section:**
   - Text color changes dynamically between `text-yellow-400` (dark mode) and `text-red-700` (light mode).
   - Added hover effects with text shadow to enhance the appearance.

3. **Features Section:**
   - Features cards now support dark mode with changes to text and background colors.
   - Updated hover effects for better interactivity in dark mode.

4. **Best Dishes Section:**
   - Placeholder elements now adapt to dark mode when data is loading (using `animate-pulse` with `bg-gray-700`).
   - Cards component supports both light and dark mode seamlessly.

5. **About Section:**
   - Adapted background and text colors for both modes.
   - Added image shadowing for better visual depth.

#### How to Test:
1. Switch your system to dark mode or toggle the theme manually in the app.
2. Navigate through the Hero, Features, Best Dishes, and About sections to ensure all components adapt correctly to dark mode.
3. Test hover effects in both modes to confirm consistency and responsiveness.

#### Closing Issues:
- Closes #57  (Dark mode implementation).

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Abhi0049k please update the branch & The signup page has some issue with navbar:
image

**Comment by AlfiyaSiddique** [comment]
@Abhi0049k any updates, If no updates found I have to close this PR

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique If not completed I would like to work on this issue

**Comment by AlfiyaSiddique** [comment]
Closing this PR due to no response

**Pull request closed without merging**
