### PR TITLE
ADD seed data

### LINKED ISSUE #360: FEATURE: Seed data
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Several pages of the website is empty in development because the local database is empty.
I want to seed some dummy data so that developers can have their time fixing the problems rather than seeing empty pages without data.
It will a command to run in the terminal and your local database will be up with all the datas that will be rendered on the site.

### Component

main meals, small bites and healthy pages.

Screenshot 2024-10-26 115137

### It should be implemented because

it allows developers to improve these pages also which is not possible if they are empty. 

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by haseebzaki-07**
## What does this PR do?

This PR creates a new file in the backend for seeding in the dummy recipes data to the database.

Fixes #360 

Screenshot 2024-10-30 134323
Screenshot 2024-10-30 134334
Screenshot 2024-10-30 144622
Screenshot 2024-10-30 145002

## How should this be tested?

Run "npm run seed" command in the backend terminal to see the changes.

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read Contributing guide
- [X] Self-reviewed my own code
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@ha.eebzaki-07 can you add about the seed data and the command in the Contributing.md?
So that the new contributors are aware of it

**Comment by haseebzaki-07** [comment]
sure @AlfiyaSiddique I will add it.

**Comment by haseebzaki-07** [comment]
hey @AlfiyaSiddique I made the changes in Contributing.md

**Comment by haseebzaki-07** [comment]
@AlfiyaSiddique please consider

**Comment by AlfiyaSiddique** [comment]
@haseebzaki-07 I think it's fair considering the value it's adding

**Pull request merged**
