### PR TITLE
FEAT: Dummy Images for errors in frontend and Grafana Prometheus implementation in Backend

### PR DESCRIPTION
**Pull request by tejasbenibagde**
This PR implements the following changes:

## Backend

1. **Prometheus**
    - Added the Prometheus to scrape the server metrics and can be seen at the `/metrics` route.
2. **Grafana**
   - Implemented using grafana inside a docker container to visualize the scraped data at route `/metrics` route.
3. **Detailed Guide**
   - Added a detailed guide in `README.md file` to setup both the Grafana and Prometheus.
4.  **Fix for Issue #118 **
    - This PR addresses the concerns raised in GitHub Issue #118 .

## Frontend
1. **Dummy Images for Error Handling**: 
   - Added placeholder images to be displayed when no recipes are available for the user or when the liked recipes list is empty. This enhances the user experience by providing visual feedback instead of a blank screen.

6. **.env.example Update**: 
   - Updated the `.env.example` file in the backend to ensure it includes all necessary environment variables required for the application setup.

7. **Fix for Issue #100 **: 
   - This PR addresses the concerns raised in GitHub Issue #100.

### CODE REVIEW

**Comment by tejasbenibagde** [comment]
@AlfiyaSiddique I'm solving multiple issues in a single PR please merge this as soon as possible because it has not issues with the base branch.

**Comment by AlfiyaSiddique** [comment]
@tejasbenibagde please resolve conflicts 
And do not solve multiple issues in one PR only, this is not accepted. Open separate PR for separate issues.
This will result into your loss of points only, that's why open separate PR for different issues that you got assigned.

**Comment by tejasbenibagde** [comment]
I opened the one PR yesterday but you did not merge. And the GSSOC event is still on the go. Do you really think I have so much time to wait for one PR to get merged and then start working on another?

**Comment by tejasbenibagde** [comment]
Also I don't know why but I started to feel like you have some issues with me.

**Comment by tejasbenibagde** [comment]
I'll try to separate this pr in two separate ones. But please give me the time when you'll be active today after 8 PM so that I can add a pull request at the same time.

**Comment by AlfiyaSiddique** [comment]
@tejasbenibagde  ^^

**Comment by tejasbenibagde** [comment]
Ok, I understand. Thank you for clarifying. For now, I'll close this one. I'll open another after 8 PM today to solve one issue, and once that's resolved, I'll open another. I hope that's fine with you.

**Comment by tejasbenibagde** [comment]
One thing I'd like to suggest to you is to use the ai code review tools similar to coderabbit. They are good and eventually help you make the more detailed and accurate code reviews in a short time and it will eventually help you save the time it takes to review the PR.

**Comment by AlfiyaSiddique** [comment]
okay, I will search about it and see if it can be integrated.
Thank you for the suggestion!

**Comment by aditya-bhaumik** [comment]
@sanjay-kv this was the pull request made before the earlier pull reques

**Pull request closed without merging**
