### PR TITLE
Implemented light and dark mode for essential components!!

### PR DESCRIPTION
**Pull request by rajgharat07**
I am trying to upload a video of the implementaion but not getting uploaded?

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 I can't see you being assigned to any issue.
You need to get assigned to issues first and then raise PR. As of now can't consider this PR. But keep it open. In case of inactivity will merge it.
Thanks for showing interest

**Comment by rajgharat07** [comment]
Ok Mam thanks a lot!

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 just in case you are interested please make a comment in issue 57,so that your PR may get accepted due to the inactivity of other contributors but please don't expect to merge it soon.

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 please update your PR

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 any updates?

**Comment by rajgharat07** [comment]
@AlfiyaSiddique Ma'am, I'm currently working on it and will provide an update by tomorrow night.

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 any updates

**Comment by AlfiyaSiddique** [comment]
@rajgharat07 please reply or have to close this PR due to no activity. You can give us a date by when you will continue.

**Pull request closed without merging**
