### PR TITLE
your activity

### PR DESCRIPTION
**Pull request by Veda273**
added your activity

## What does this PR do?

added a your activity section in the dashboard

since the comments are disappearing once refreshed.. i was unable to work on it efficiently, yet i managed  to  add a section named your activity in the dashboard.. I tried my best to work on it but fixing the comments too.. and then working on the your activity section, seemed a bit of overload for me.. @AlfiyaSiddique ,I request you to review my work upto now..

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Veda273  fix merge conflicts and tag the issue

**Comment by Veda273** [comment]
@AlfiyaSiddique  #292 resolved please check

**Comment by AlfiyaSiddique** [comment]
@Veda273 you have hardcoded it, this is not accepted, make it dynamic. Also, the code is not proper there are unnecessary '====':
image

Also instead of adding it in the below profile, make a separate section like My Recipe and Liked Recipe and add the activities.

**Comment by AlfiyaSiddique** [comment]
@Veda273 any updates?

**Comment by Veda273** [comment]
@AlfiyaSiddique No.. I am actually facing issues while connecting to backend and database that i created locally.. so i am not opening any new issue..

**Comment by AlfiyaSiddique** [comment]
@Veda273 do you need any help with local setup or do you want to close this PR and unassign you?

**Comment by Veda273** [comment]
@AlfiyaSiddique yes, you can unassign me.

**Comment by AlfiyaSiddique** [comment]
- [ ]

**Pull request closed without merging**
