### PR TITLE
Integrated Testimonials Carousel with backend and added new APIs with redesigned modal

### LINKED ISSUE #370: FEATURE: Connect Feedback Database to Testimonials Section
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Currently, the feedback from users is stored in the database but is not displayed in the testimonials section of the website/application. This issue aims to connect the feedback database to the testimonials section, so that user feedback can be dynamically pulled and displayed.

### Component

/frontend/src/pages/landing

### It should be implemented because

- Increase User Trust: Genuine testimonials from actual users are powerful social proof, helping new users make informed decisions.
- Enhance User Engagement: Highlighting positive feedback may encourage existing users to leave their own reviews, creating a continuous feedback loop.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Description
This PR implements a testimonials carousel by redesigning the feedback submission API and updating the feedback modal and form. The integration aims to enhance user experience by allowing users to submit and view feedback dynamically.

- Closes #370 
### Changes Made
1. **Redesigned API for Submitting Feedback:**
   - Added endpoint for submitting feedback: `/submitFeedback`
   - Added endpoint for retrieving all feedback: `/getFeedback`
   - Implemented a check to allow feedback submission only if the user is logged in, which helps to prevent database clutter from unauthorized submissions.
2. **Redesigned Feedback Modal:**
   - Updated the feedback modal UI to meet the design requirements of the testimonials carousel, ensuring user-friendliness and aesthetic alignment with the application.

3. **Redesigned Feedback Form:**
   - Modified the feedback form to accommodate additional fields or changes required for the testimonials, improving validation and user guidance.

4. **Integrated All Components:**
   - Ensured that the feedback submission and retrieval processes are fully integrated with the testimonials carousel feature, verifying that all changes work together smoothly.

## How should this be tested?

- Fill the feedback form (You need to login for it)
- Refresh the Page and see if the submitted feedback has appeared in the carousel

## Video:
- Flow of Process

https://github.com/user-attachments/assets/51108a23-de9d-47ae-b528-f2084027f225

-  Error handling

Screenshot 2024-11-01 at 12 55 46 PM

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Note: testimonial section won't appear on homepage is there are none testimonial present to keep it clean.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean can't see the testimonial section in deploy preview:
It is visible in actual deployed link but not on your preview:
image

This probably means you have lost some changes while resolving conflicts or updating this branch.
Can you please check and fix this.

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique no. The testimonials are connected with db, and you need to post some feedbacks to actually see them appear

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique kindly read the how to test section in my pr

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean You are right! The changes look fine

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique do you have any other issue up for grab which I can work on?

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean can you implement the delete functionality of accounts??
Also, if the deletion of feedback is in user control it will be better:
You can open separate issues for these?

**Comment by IkkiOcean** [comment]
> @IkkiOcean can you implement the delete functionality of accounts??
> Also, if the deletion of feedback is in user control it will be better:
> You can open separate issues for these? 

Okay sure

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique one more thing, while looking at the contributors page I found it basic. I can implement a more aesthetic and modern design for the contributor page. 
demo:

Uploading contribute.mp4…

Should I raise a issue for this?

**Comment by AlfiyaSiddique** [comment]
image

Can see the uploaded item @IkkiOcean 
You can raise issue but it will be assigned only once the design is approved

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique my bad, check it now

**Comment by AlfiyaSiddique** [comment]
The video reference looks good but still it looks too fancy. We need something subtle. You can make changes in the page according to your design idea and raise the issue with the implemented part. You will get feedback on that.

**Comment by IkkiOcean** [comment]
> The video reference looks good but still it looks too fancy. We need something subtle. You can make changes in the page according to your design idea and raise the issue with the implemented part. You will get feedback on that.

okay sure.

**Pull request merged**
