### PR TITLE
Set the limit in text line Cards.jsx

### PR DESCRIPTION
**Pull request by Mansi07sharma**
Set the number of lines of text is 4

If the text is going out of line 4 then it will be look like **...**  as you want 

#173 issue is solved 

My previous pull request #224  kindly close it and see this @AlfiyaSiddique .

If you satisfy with it kindly merge it and add labels of level2 or level3 or if you want any more changes then tell me.

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma why did you open two different pull request, you could have push the changes in the same PR only

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique sorry for that , by mistake I done it.. so what to do next.. close it and reopen that pull request? Or it is okk . 

Next time it will not repeat.

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique okay I do it

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique kindly check it again I closed previous pull request now it is main.

Please check it.

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma just want to confirm if you moved the closed PR code to this PR.

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma the issue still exists please check the deploy preview recipe page:
https://deploy-preview-231--delightful-daifuku-a9f6ea.netlify.app/

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique please check it

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma working fine!
Thanks for the contribution 
Please resolve the conflict and update to the latest commit and Then I will merge your PR.

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique Good to hear it. I will do it.

Can you add level2 or level3 ? It's a humble request to you.

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique done

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
Looks good @Mansi07sharma 
Thanks for your contribution

**Pull request merged**
