### PR TITLE
Github Workflow : Notify Contributors When Pull Requests Are Merged

### LINKED ISSUE #205: FEATURE: Github Workflow : Notify Contributors When Pull Requests Are Merged
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Notify Contributors When Pull Requests Are Merged

### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

Hey @AlfiyaSiddique   Please assign me this issue with "level3"

### Component

N/A

### It should be implemented because

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by samyak-aditya**
Notify Contributors When Pull Requests Are Merged
fixed #205 
### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya one improvement.
Can you please tag the PR owner in this message so that it looks more personalized?

Also, add the output screenshot by opening and merging a PR on your fork

**Comment by samyak-aditya** [comment]
@AlfiyaSiddique good idea, let me do that

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya any updates?

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya have to close this if no updates received

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I have updated the code to include PR owner
now they will be notified.

**Comment by samyak-aditya** [comment]
Please give it a "level2" or "level3" , whatever you think is appropriate
Thanks

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya please add a ss of the output by creating a test PR on your fork

**Comment by samyak-aditya** [comment]
@AlfiyaSiddique let me do that

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
Giving level 2 this time, but just to mention that less effective PRs are more likely to get level 1. So not to expect more:)

**Comment by samyak-aditya** [comment]
@AlfiyaSiddique Hehehe Thanks for that :P

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya there's a bug instead of PR creators name it is tagging owner

**Comment by samyak-aditya** [comment]
Yes I just Noticed it 
let me fix it

**Comment by AlfiyaSiddique** [comment]
Please fix this asap, and raise a new PR for this I am removing the label from here and will add it to the fix

**Comment by samyak-aditya** [comment]
Okay sure

**Pull request merged**
