### PR TITLE
Add the height and overflow in Cards.jsx

### PR DESCRIPTION
**Pull request by Mansi07sharma**
Add the height 15vh and overflow hidden

#173

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma can you please tag the issue for which you have raised this PR.

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique Done Please check it

**Comment by AlfiyaSiddique** [comment]
@Mansi07sharma, the text is getting half-hidden due to the fixed height. Can you fix this? If there is more text, just show it as  `...`
image

**Comment by Mansi07sharma** [comment]
@AlfiyaSiddique sure I will do it.

**Pull request closed without merging**
