### PR TITLE
Added Follow Feature to User Profile (Backend & Frontend Integration)

### LINKED ISSUE #424: FEATURE:  Create User Profile Page and Follow Feature
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

#### Description
Implement a dedicated user profile page that displays information about individual users, including their bio, followed recipes, and feedback. Additionally, introduce a functionality that allows users to follow each other, enhancing community interaction and engagement on the platform.

#### Acceptance Criteria
1. **User Profile Page:**
   - Create a new route for user profiles, accessible via their username or user ID.
   - The profile page should display:
     - User's profile picture
     - Username
     - Bio
     - List of recipes created by the user
     - List of feedback given by the user
     - A "Follow" button if the current user is not already following them.

2. **Follow Feature:**
   - Implement functionality to follow/unfollow other users.
   - When the "Follow" button is clicked:
     - Update the backend to add the user to the follower list of the current user.
     - Change the button to "Unfollow" to indicate the current status.
   - Ensure that the list of followers and following is updated accordingly in the database.

### Component

it will be a new page. /UserPage.jsx since current component is configured for logged in user not others.

### It should be implemented because

1. **Enhanced User Engagement:**
   - Users can interact with each other by following profiles, leading to increased engagement on the platform. This creates a community feel and encourages users to explore content from others.

2. **Personalized Experience:**
   - By allowing users to follow others, they can curate their feed with recipes and feedback that interest them, providing a more tailored experience. This personalization can lead to higher user satisfaction and retention.

3. **Networking Opportunities:**
   - Users can connect with others who share similar interests in recipes and cooking, fostering networking opportunities. This can lead to collaborations, shared tips, and a supportive community.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
### **Description:**
I implemented a follow/unfollow feature on the user profile page. This will allow users to follow other users and see their followers/following counts. The feature includes both backend controller logic to manage user relationships and frontend integration to allow users to follow/unfollow others directly from their profile.

#### **Backend (Controller & API Logic):**
-  Create a `toggleFollowUser` controller to handle follow/unfollow actions.
-  The controller should:
  - Accept a `userId` from the logged-in user and a `targetUserId` from the request parameters.
  - Check if the logged-in user is already following the target user.
  - If following, remove the user from the logged-in user's following list and vice versa.
  - If not following, add the user to the logged-in user's following list and vice versa.
  - Update the follower and following counts for both users.
  - Return the updated counts and a success message upon completion.
- Update the `User` model if necessary to include the necessary fields (followers and following arrays).

#### **Frontend (Profile Integration):**
- Create a button  on the user profile page for the follow/unfollow action.
  - Display the button as `Follow` if the logged-in user is not following the target user.
  - Change the button to `Following` if the logged-in user is already following the target user.
- Call the backend API to toggle the follow/unfollow status when the button is clicked.
- Display the updated follower and following counts dynamically.
- Add loading states or error handling for the follow/unfollow action.

- Closes #424 

### video

https://github.com/user-attachments/assets/0c60f3b6-1ef2-46ba-8e8d-c46f7b300ecc

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean, can you change the profile page's red background as we discussed before?

**Comment by IkkiOcean** [comment]
> @IkkiOcean, can you change the profile page's red background as we discussed before?

I added a gradient to it. what should I change it to?

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean can see the gradient because the deployment failed due to a syntax error:
image

**Comment by AlfiyaSiddique** [comment]
Please fix it

**Comment by IkkiOcean** [comment]
> Please fix it

that must be a merge conflict cause.
btw is this image good as the background
image

**Comment by AlfiyaSiddique** [comment]
Yeah for now we can go with this, please make the changes

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique I completed the changes

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
