### PR TITLE
Updated ui of Login page

### LINKED ISSUE #28: Improving UI/UX of SignUp Page with user freindly experience..
The signup now looks so simple with form element being so simple. What if, the complete signup page can be enhanced with good layout, components, images, hover effects, icons...having text field with good designs....

Please assign this project under GSSoC'24 Extd..
I am GSSoC'24 Extd. Contributor...
Screenshot 2024-10-02 at 4 16 51 PM

### PR DESCRIPTION
**Pull request by sushil-sagar05**
issue #28 
Updated the ui of login page and make user Friendly and interactive

Fixes #28 
previous
TastyTrails-prevLoginPage
After Updation
newloginTastyTrails

### Required

- [ X] Filled out the "How to test" section in this PR
- [ X] Read Contributing guide
- [X ] Self-reviewed my own code
- [X ] Checked for warnings, there are none
- [X ] Removed all `console.logs`
- [X ] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique kindly review this pr of mine.. closed the first one due to some Error ...And please tell me why here is showing resolve conflicts i saw the code everything looks fine and running on localhost then why here showing conflicting files in Login.jsx

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 why open two different PR for the same issue?

**Comment by sushil-sagar05** [comment]
> @sushil-sagar05 why open two different PR for the same issue?

i close the previous pr because giving me error resolve conflicts so i think after reopen pr will solve my problem but nothing works it still giving me same issue @AlfiyaSiddique

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique please review this pr and tell me if i can update it or it is good and merge this pr as soon as possible because I have my midesems running from 24  so i can't focus more here for that reasons.. Please you are replying so lately

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 this PR also have merge conflicts. I can't merge any PR with merge conflicts because it will not get deployed. You have to learn how to resolve merge conflicts. And reopening a new PR will not fix merge conflicts

**Comment by sushil-sagar05** [comment]
here after that all step 
merge conflits
Still showing resolve confllicts here

**Comment by sushil-sagar05** [comment]
> here after that all step merge conflits Still showing resolve confllicts here

@AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@iitzIrFan can you please help him

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 did you push the code after resolving the conflicts?

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique what happens here please see once it is showing merging is blocked

**Comment by iitzIrFan** [comment]
@sushil-sagar05 Firstly syn your fork with the main project. You can do this by going to this projects fork and there will be a btn around the project clone section and syn your fork and then try again. It should resolve the merge conflict or else tell me the issue from your side to get it solved.

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 do not delet the Pr it's fine

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 your merge conflict is resolved the merging is blocked is due to the Branch security rule. It will get green after I approve your Pr

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 I can't see the new Signup page's new design, it's the same as the before one only, why is that?
image

Did you open a new PR for it?

**Comment by AlfiyaSiddique** [comment]
There is issue #310  that has both the changes . And as of now there are 2 PRs open for the same issue by you. This is confusing which PR has which change and which PR to consider. @sushil-sagar05 please clarify

**Comment by sushil-sagar05** [comment]
> @sushil-sagar05 I can't see the new Signup page's new design, it's the same as the before one only, why is that? image
> 
> Did you open a new PR for it?

yess for signup page #310

**Comment by AlfiyaSiddique** [comment]
Then resolves that's PR conflicts as well, and it has the login page changes as well, then why you have opened this PR?

**Comment by AlfiyaSiddique** [comment]
No worries @sushil-sagar05 just fix both the Prs properly, Then I will test the outputs and review the code and then both of them can be merged.

**Comment by sushil-sagar05** [comment]
> No worries @sushil-sagar05 just fix both the Prs properly, Then I will test the outputs and review the code and then both of them can be merged.

this pr part is resolve na?

**Comment by AlfiyaSiddique** [comment]
Yes this Prs merge conflict is resolved

**Comment by AlfiyaSiddique** [comment]
I just wanted to let you know that the merge conflict can occur again. Every time a PR is merged to the main branch there are chances that your PR will have conflicts. You can learn how to resolve conflicts. As of now there is no conflicts

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique so kindly review and accept my both pr asap b/c i have only time for tomorrow so if you request for any  change , i will do asap

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 This is also failing:
image

Please fix it

**Comment by AlfiyaSiddique** [comment]
>@AlfiyaSiddique so kindly review and accept my both pr asap b/c i have only time for tomorrow so if you request for any change , i will do asap

@sushil-sagar05 cannot merge the PR until all errors are resolved and it is approved. I am sorry to hear that you won't be contributing after tomorrow but No problem, if you can't give time to this project. Just clarify once before you stop working on the issue so that it can be assign to someone else

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 the deployment is successful.
the change is not implemented correctly, neither is the design correctly aligned nor responsive.
Also, you have added 3 new images and used only 2 of them in the code so please remove the one which is not used
image

image


I appreciate you but Not satisfied with the work!
Now you can choose if you want to improve it or should I merge like this, you will get the points but not really a good work

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique hey sorry for all that stuff 
i update all the responsive part of login in this commit 
screenshot
newLoginTastytrailsnew


https://github.com/user-attachments/assets/96c2da40-e1cd-44a3-9d73-c721c768ced4

cosider this pr as enhancing ui of login part

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 looks good,
But the same footer issue, can you cross-check once the below:
>Okay, @sushil-sagar05 can you check the footer component file and find the GogleTranslator component if it has a column beside it can you remove it?
If no comma is present just share the screenshot of code of that part

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique update the review and if all set to go then merge it please

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 deploy is failing due to an error in Signup.jsx:
image

**Comment by sushil-sagar05** [comment]
hey @AlfiyaSiddique please see this ..

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 great work! 👏🏻👏🏻👏🏻
just resolve the merge conflicts and then it will be merged

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique see

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique thankyou for merging this pr finally after 2 weeks so many conflicts and ui change this merged ..Thankyou for you constant support as a mentor in this journey of mine , i started as a noob but today here i fell i learnt many things in open source all because of you.. Thanking you once again :>

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 keep going! keep up the good work:)

**Pull request merged**
