### PR TITLE
Create User Profile Page for Viewing Other Users' Recipes and Liked Recipes

### LINKED ISSUE #424: FEATURE:  Create User Profile Page and Follow Feature
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

#### Description
Implement a dedicated user profile page that displays information about individual users, including their bio, followed recipes, and feedback. Additionally, introduce a functionality that allows users to follow each other, enhancing community interaction and engagement on the platform.

#### Acceptance Criteria
1. **User Profile Page:**
   - Create a new route for user profiles, accessible via their username or user ID.
   - The profile page should display:
     - User's profile picture
     - Username
     - Bio
     - List of recipes created by the user
     - List of feedback given by the user
     - A "Follow" button if the current user is not already following them.

2. **Follow Feature:**
   - Implement functionality to follow/unfollow other users.
   - When the "Follow" button is clicked:
     - Update the backend to add the user to the follower list of the current user.
     - Change the button to "Unfollow" to indicate the current status.
   - Ensure that the list of followers and following is updated accordingly in the database.

### Component

it will be a new page. /UserPage.jsx since current component is configured for logged in user not others.

### It should be implemented because

1. **Enhanced User Engagement:**
   - Users can interact with each other by following profiles, leading to increased engagement on the platform. This creates a community feel and encourages users to explore content from others.

2. **Personalized Experience:**
   - By allowing users to follow others, they can curate their feed with recipes and feedback that interest them, providing a more tailored experience. This personalization can lead to higher user satisfaction and retention.

3. **Networking Opportunities:**
   - Users can connect with others who share similar interests in recipes and cooking, fostering networking opportunities. This can lead to collaborations, shared tips, and a supportive community.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
### **Description:**

This PR introduces a new **Profile Page** that displays the profile of other users on Platform, the following features:
- **User's Recipes**: A section that lists all recipes created by the user.
- **Liked Recipes**: A section that lists all recipes liked by the user.

This functionality is integrated with the backend to fetch the recipes and liked recipes data from the server.

### **Features Added:**
1. **Frontend**:
   - Created a new page Profile to display the other user's profile information.
   - Displayed the user's created recipes and liked recipes.
   - Added a loading spinner while fetching data from the backend.
   - Displayed an error message in case of failure to fetch data.

3. **Integration**:
   - Integrated the frontend with the backend API to fetch the user's recipes and liked recipes dynamically based on the logged-in user.

Fixes #424 

## How should this be tested?

- Go to testimonials present and click on the username in it( Its temporarily till we make a user search feature)
- It will redirect to profile of that user directly.

### Video:

https://github.com/user-attachments/assets/e42072c4-dd43-47a6-a262-34c2b6179e86

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique Can I implement Follow feature with its backend API in another PR as creating a whole new page with backend integration was already a big task, so I decided to PR this separately.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean Sure, you can work on it with 2 Prs, will assign labels on each as it is a big feature addition.
One feedback: 
image

Currently, this looks like a LinkedIn layout but I think the Instagram profile layout suits this site more.
Can you change that? Let me know what you think

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique I think it's more like a blog site and users of them use attractive banners so to show what they are interested in. Like they can upload a banner there and it would enhance the looks of the page. One more thing, currently Instagram doesnt use banner because its a mobile application at main and doesnt need them, since most of the web application social medias use them for making there pages look more filled and attracting for example twitter and LinkedIn

**Comment by IkkiOcean** [comment]
> > @AlfiyaSiddique I think it's more like a blog site and users of them use attractive banners so to show what they are interested in. Like they can upload a banner there and it would enhance the looks of the page. One more thing, currently Instagram doesnt use banner because its a mobile application at main and doesnt need them, since most of the web application social medias use them for making there pages look more filled and attracting for example twitter and LinkedIn
> 
> Right Agree! But can we change the banner section red background to something else, just plain red does not look good

okay I will change it during the follow feature implementation. would that be good? I am working on it and the PR will be ready till the midnight. you can merge it whenever you get free.

**Comment by AlfiyaSiddique** [comment]
Is this PR ready for review?

**Comment by IkkiOcean** [comment]
> Is this PR ready for review?

yeas. you need to go through any testimonial to see that users profile

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
