### PR TITLE
fixes #26 Add Recipe 

### LINKED ISSUE #26: Error on Adding Recipe
Hey @AlfiyaSiddique,
I noticed when adding a recipe, the server responds with 404. I would like to work on this issue.
Please assign me this issue under GSSOC Extended and Hacktoberfest 
Below is the screen shot of the issue.
image
image

### PR DESCRIPTION
**Pull request by ZayedShahcode**
The code seemed perfect. There was one simple mistake in authorization header which I believe is the cause of error.

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode please tag this PR is related to which issue. Tag the issue number

**Comment by ZayedShahcode** [comment]
closes #26

**Comment by ZayedShahcode** [comment]
@AlfiyaSiddique I added the issue number in title and comments. Is that right?

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode this is an imp issue, It is blocking many other workflows. Please fix it as soon as possible. 
If you are occupied please allow me to assign to someone else.

**Comment by ZayedShahcode** [comment]
@AlfiyaSiddique I tested in my local server and it works. Only change I did was what i committed i.e 'token' instead of "TOKEN".  Could you please  check if you provided the correct read and write permissions to your github api token. For testing I provided all the permissions to my api token. Below is the proof.


https://github.com/user-attachments/assets/521e7542-8ee7-4e31-b9e5-c56b71cb4a50

**Comment by AlfiyaSiddique** [comment]
@ZayedShahcode This does not fix the issue on a production level. 
This is due to some configuration issues from the deployment side and has been fixed.
Hence closing this issue and PR.
Thanks for drawing our attention to this issue.
We apologize as we cannot give points on this since no code change is needed

**Pull request closed without merging**
