### PR TITLE
Fixed #50 :Auto-Label Issues and Pull Requests on Creation 

### LINKED ISSUE #50: Feature: Auto-Label Issues and Pull Requests on Creation
**Description:**
I propose to implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
  - **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

Hey @AlfiyaSiddique  please assign me this task with label "gssoc-ext", "Hacktoberfest-accepted" and "level1"

### PR DESCRIPTION
**Pull request by samyak-aditya**
Fixed #50 

**Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

Implementing this "auto-label" workflow will enhance project organization

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya can you open some issue on you fork and share the output image here

**Comment by samyak-aditya** [comment]
Okay let me do that

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique Here is the Screenshot
its working 💯 

Screenshot 2024-10-06 031521

**Comment by AlfiyaSiddique** [comment]
Great @samyak-aditya 
Merging now!

**Pull request merged**
