### PR TITLE
Bug fix recipie deletion issue #43

### PR DESCRIPTION
**Pull request by sadath2001**
Hi,

Related issue: #43 

I added a simple line which will enforce the refresh of window once the recipie is deleted 
File modified: Dashboard.jsx

Kindly add this under gssoc ext and hacktober

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@sadath2001 your branch has merge conflicts.
Please update the branch and resolve the conflicts

**Review by sadath2001 — COMMENTED** [review]
All good

**Comment by AlfiyaSiddique** [comment]
@sadath2001 can you please do this without reloading the page? I think you can use react states for this.
 Because if it reloads it does not give a good user experience.
 Also, update your branch and resolve conflicts.

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , sure I'll review it once. Thanks for the feedback

**Pull request closed without merging**
