### PR TITLE
Fixes issue #9: <fixed signup page>

### PR DESCRIPTION
**Pull request by paramveer665**
Fixes Issue #9 
This is regular on default theme. Indentation was fixed by Prettier extension in VS Code not intentional

image

This is Signup page on dark theme.

image

This is after my fix on same signup page in dark theme.

Signup page on light theme and dark theme after my font fix and added better tailwind shadow
Dark
image

Light
image

Kindly add this under Hacktoberfest

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@paramveer665 
Thanks for your interest but please note: **Do not open PRs directly without getting assigned to an issue.**
This way someone else may have also working on the same issue and this results in loss of work.
This is against the rule.

**Comment by AlfiyaSiddique** [comment]
Still we will see if this PR can be merge or not as it is in discussion with another contributor

**Comment by AlfiyaSiddique** [comment]
@paramveer665 on which device does the dark theme appearing, is it mac?
Cause I check on my device chrome but it does not have any dark appearance in even dark mode.

**Comment by AlfiyaSiddique** [comment]
Also, can you attach a detailed screen recording of the output as I cannot see it on my device

**Comment by paramveer665** [comment]
> @paramveer665 Thanks for your interest but please note: **Do not open PRs directly without getting assigned to an issue.** This way someone else may have also working on the same issue and this results in loss of work. This is against the rule.

I understand thank you very much for informing me this.

**Comment by paramveer665** [comment]
> @paramveer665 on which device does the dark theme appearing, is it mac? Cause I check on my device chrome but it does not have any dark appearance in even dark mode.

I am using windows + brave browser where if I change my system/browser them. Website theme changes too.

**Comment by paramveer665** [comment]
> Also, can you attach a detailed screen recording of the output as I cannot see it on my device

surely I will attach a video of the same

**Comment by paramveer665** [comment]
https://github.com/user-attachments/assets/7d9081ff-b781-4224-b960-4d53d2e7468c

Here is the preview as you had requested.

**Comment by AlfiyaSiddique** [comment]
@paramveer665  in the given video:
The fields of the signup page are also black on a light theme please fix it:
Also, please do not give the full width to the first and last name fields as it makes the form look too big keep, it as it was before.

**Comment by paramveer665** [comment]
> @paramveer665 in the given video: The fields of the signup page are also black on a light theme please fix it: Also, please do not give the full width to the first and last name fields as it makes the form look too big keep, it as it was before.

Hello @AlfiyaSiddique, completed all the mentioned changes and made a pull request. Please assess it 


https://github.com/user-attachments/assets/c481086e-a08b-4d89-aa20-19522eb83fa7

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
