### PR TITLE
Frontend loading skeleton integrated, with necessary changes

### LINKED ISSUE #24: Add Loading Skeleton Component
I would like to propose adding a loading skeleton to the project to enhance the user experience during data fetching or other loading states.

### PR DESCRIPTION
**Pull request by AlaminPu1007**
# Add Loading Skeleton to Frontend

This PR implements a loading skeleton component in the frontend to improve user experience during loading states. The skeleton loader provides a visual placeholder while content is being fetched from the backend, replacing blank or loading spinners with a modern and polished design.

# Attached a video for better understanding 
[loading-skeletion.webm](https://github.com/user-attachments/assets/a76ea206-b1de-46fd-a72c-49d6a063e6d5)

Fixes #24

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
Thank you for your contribution! @AlaminPu1007 
Great Work.
Just one question: Have you added the skeleton feature in the World's Best Dishes Section of the Landing Page?
Asking cause I can't see it.
If no can you please add there as well.

**Comment by AlfiyaSiddique** [comment]
Also one piece of feedback, 
Do not make unnecessary and excessive formatting in the code this makes difficult to review the PR.

**Comment by AlaminPu1007** [comment]
> Thank you for your contribution! @AlaminPu1007 Great Work. Just one question: Have you added the skeleton feature in the World's Best Dishes Section of the Landing Page? Asking cause I can't see it. If no can you please add there as well.

I will take a quick look back at it

**Comment by AlaminPu1007** [comment]
@AlfiyaSiddique 
image

**Comment by AlfiyaSiddique** [comment]
@AlaminPu1007 please resolve the merge conflicts and update the branch with the latest. Will merge now!
Thanks for your contribution

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlaminPu1007** [comment]
@AlfiyaSiddique  i have resolved the conflicts. Can check it now.

**Pull request merged**
