### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nishant4500**
issue #161

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@nishant4500 please tag the issue for which you raised this PR.

**Comment by nishant4500** [comment]
#161

**Comment by AlfiyaSiddique** [comment]
Also, Add one more point  - tag the issue when raising PRs like fixes #issue_number :) 
Frame this sentence well

**Comment by nishant4500** [comment]
ok, i think this idea comes from me haha

**Comment by nishant4500** [comment]
@AlfiyaSiddique can you please label me

**Pull request merged**
