### PR TITLE
Updated footer

### LINKED ISSUE #15: Add footer
Add footer for better ui experience

### PR DESCRIPTION
**Pull request by shivanjalikarande**
## What does this PR do?

Fixes #15 

All footer elements are placed with correct spacing. Added hovering effects to all elements & size of social media icons increases.
Made footer responsive to smaller screens as well

## How should this be tested?

Screenshot (71)
Screenshot (72)

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by shivanjalikarande** [comment]
@AlfiyaSiddique please review PR, suggest changes if any and add label accordingly.

**Comment by AlfiyaSiddique** [comment]
@shivanjalikarande  The footer does not look good:
image

Unnecessary too much space.
Also, you have to make the layout given in the issue.
No need to add a hover effect or increase the font and symbol size keep it as it was before.
Please improve
image
Also no need to add newsletter when implementing above

**Comment by shivanjalikarande** [comment]
Okay, I will make suggested changes

**Comment by shivanjalikarande** [comment]
@AlfiyaSiddique I have improved footer according to given design.

Screenshot:

Screenshot (88)

Please review the changes.

**Comment by AlfiyaSiddique** [comment]
@shivanjalikarande looks great, please update the PR

**Comment by AlfiyaSiddique** [comment]
@shivanjalikarande some improvements:
there is margin space in the sides of the copyright background:
image

Please remove it and make the copyright background to cover the whole space of that part 
The Language translator is missing please move it back

**Comment by shivanjalikarande** [comment]
Okay, @AlfiyaSiddique I will do changes & will check for conflict

**Comment by shivanjalikarande** [comment]
> @shivanjalikarande some improvements: there is margin space in the sides of the copyright background: image
> 
> Please remove it and make the copyright background to cover the whole space of that part The Language translator is missing please move it back

@AlfiyaSiddique, Could you please check whether after refreshing page google translator is visible or not? Just for confirmation so I can proceed further

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
