### PR TITLE
Enhanced the scroll behavior which was caused by footer

### PR DESCRIPTION
**Pull request by Sarthakkashyapp**
Enhanced the unusual scroll behavior which was caused by footer now the contents will not hide irrespective of the screen size, and it is also responsive now giving a great experience to the user. It also made the footer responsive in every device.

issue resolved : #241 

https://github.com/user-attachments/assets/5f420962-f985-4be7-bc22-f8ed2b4b3556

Screenshot 2024-10-17 122903

Screenshot 2024-10-17 122832

Thankyou @AlfiyaSiddique for assigning me this issue. It was great working on this project 😊. Also please add the labels **hacktoberfest-accepted**, **gssoc-ext** and **level-1**. Happy coding.

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp looks good 
Please update your Pr, will merge then

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp looks good 
> Please update your Pr, will merge then

Sure @AlfiyaSiddique 
Please correct me if I'm wrong to update I only need to commit again and then push again right.
Thankyou for your feedback 😊

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp To update your PR you have to run the `git pull origin master` on the your local branch i.e scroll-enhancement 
This fetches the latest already merge code of others to your local.

In the below image, you can see it says Conflicting files:  There is only one Footer.jsx, At times there can be more.
This means the latest code of the repo has some changes in the same place where you made a change in your local branch.
So after you pull, if you are using VS code it will show you a button to resolve conflicts in the merge editor. From that editor, you can see your current code and the already deployed code side-by-side and then you have to fix the code at lines where it is conflicting (this is highlighted by VS code). Then there are three options Accept Incoming, Accept Current, or Combination. You have to understand the code and decide which option to choose such that neither the deployed code logic nor your code changes get lost 
image

Hope this helps, if the above description is not clear please find some youtube video on resolving merge conflicts

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp To update your PR you have to run the `git pull origin master` on the your local branch i.e scroll-enhancement This fetches the latest already merge code of others to your local.
> 
> In the below image, you can see it says Conflicting files: There is only one Footer.jsx, At times there can be more. This means the latest code of the repo has some changes in the same place where you made a change in your local branch. So after you pull, if you are using VS code it will show you a button to resolve conflicts in the merge editor. From that editor, you can see your current code and the already deployed code side-by-side and then you have to fix the code at lines where it is conflicting (this is highlighted by VS code). Then there are three options Accept Incoming, Accept Current, or Combination. You have to understand the code and decide which option to choose such that neither the deployed code logic nor your code changes get lost image
> 
> Hope this helps, if the above description is not clear please find some youtube video on resolving merge conflicts

Thankyou so much for guiding @AlfiyaSiddique I'll do it today itself.

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique on running command git pull origin master on my local branch I don't know why but it is showing me already up to date 
I am a little confused can you help me please

**Comment by AlfiyaSiddique** [comment]
Okay @Sarthakkashyapp  if it's up to date, could you push it?
Run: `git push origin head`

**Comment by Sarthakkashyapp** [comment]
> Okay @Sarthakkashyapp if it's up to date, could you push it? Run: `git push origin head`

okay on my local branch right? @AlfiyaSiddique

**Comment by Sarthakkashyapp** [comment]
> Okay @Sarthakkashyapp if it's up to date, could you push it? Run: `git push origin head`

on git push origin head it is showing everything up-to-date.

**Comment by Sarthakkashyapp** [comment]
@AlfiyaSiddique is everything okay now? is it merged?

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@Sarthakkashyapp good to go, merging now

**Comment by Sarthakkashyapp** [comment]
> @Sarthakkashyapp good to go, merging now

Thankyou so much @AlfiyaSiddique by far the best maintainer I've connected with always replying to each and every comment that too in a very explaining way thankyou so much 😊

**Pull request merged**
