### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nishant4500**
update with more intersting

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@nishant4500  did you raised issue for this PR?

**Comment by nishant4500** [comment]
Yes

**Comment by AlfiyaSiddique** [comment]
Please tag the issue number here

**Comment by nishant4500** [comment]
Oh sorry I didn't raise the issue

**Comment by nishant4500** [comment]
@AlfiyaSiddique can u assign me

**Comment by AlfiyaSiddique** [comment]
Did you raise the issue @nishant4500, if yes then please tag the issue number. Also please note that the issue can only be assigned if it's a valid issue. I will go through your opened issue and let you know if it can be assigned or not.

**Comment by AlfiyaSiddique** [comment]
@nishant4500 any updates?

**Comment by nishant4500** [comment]
#161

**Comment by AlfiyaSiddique** [comment]
@nishant4500 #161 already has a Pr merge. We do not need these changes.
Thanks for showing interest. Closing this.
Please open issue first from next time and get assigned

**Pull request closed without merging**
