### PR TITLE
Add Dummy Images for Error Handling and New Routes; Update .env.example

### PR DESCRIPTION
**Pull request by tejasbenibagde**
This PR implements the following changes:

1. **Dummy Images for Error Handling**: 
   - Added placeholder images to be displayed when no recipes are available for the user or when the liked recipes list is empty. This enhances the user experience by providing visual feedback instead of a blank screen.

2. **.env.example Update**: 
   - Updated the `.env.example` file in the backend to ensure it includes all necessary environment variables required for the application setup.

4. **Fix for Issue #100 **: 
   - This PR addresses the concerns raised in GitHub Issue #100.

5. **Example Screenshots**:

fix1
fix2
mainmeals
smallbytes

**Notes**:
- Please review the changes, especially the implementation of dummy images and the new routes, for potential impacts on existing functionality.

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@tejasbenibagde  please update your Pr and resolve conflicts

**Comment by tejasbenibagde** [comment]
Hello @AlfiyaSiddique  I have fixed the conflicts. Please merge this PR with the appropriate tags.

**Comment by AlfiyaSiddique** [comment]
@tejasbenibagde Some improvements in final output:
1. Can you change the image colors to red so that it match with the current color theme. The illustration site you are using must have feature to change color. If not please add images with relevant color theme.
2. change the text `Oops! Something went wrong with the server.` to `Oops! Something went wrong, we are fixing it.`. something like this
3. The image added in profile recipe page is too big that it add a vertical scroll bar, make it small such that the scroll bar do not appear. 
4. Add the text `Let's cook some delicious recipes` in profile recipe page below image.

**Comment by tejasbenibagde** [comment]
I actually added whatever Images I found on the internet cause that would take too much of a time. You are free to change them according to your taste. as for the text I'll change it as soon as possible.

**Comment by tejasbenibagde** [comment]
@AlfiyaSiddique, I've updated the text from `Oops! Something went wrong with the server.` to `Oops! Something went wrong, we are fixing it.` Regarding the images, could you please share them? I believe they could use some improvement in terms of design. 
As for points 3 and 4, I’ll take care of those today, so please bear with me until then.

**Comment by AlfiyaSiddique** [comment]
> I actually added whatever Images I found on the internet cause that would take too much of a time. You are free to change them according to your taste. as for the text I'll change it as soon as possible.
>Regarding the images, could you please share them? 

@tejasbenibagde  the main issue purpose is to add images if I only have to find the images and give you than it is not valid issue. You have to find images as per the color theme and add it then only this PR can be merged.
you can use this site to find some: https://undraw.co/search

**Comment by tejasbenibagde** [comment]
Ok I'll attach them today.

**Comment by tejasbenibagde** [comment]
I'm closing this PR and opening a new one with updates you have mentioned

**Pull request closed without merging**
