### PR TITLE
Enhance/UI of signup

### LINKED ISSUE #28: Improving UI/UX of SignUp Page with user freindly experience..
The signup now looks so simple with form element being so simple. What if, the complete signup page can be enhanced with good layout, components, images, hover effects, icons...having text field with good designs....

Please assign this project under GSSoC'24 Extd..
I am GSSoC'24 Extd. Contributor...
Screenshot 2024-10-02 at 4 16 51 PM

### PR DESCRIPTION
**Pull request by sushil-sagar05**
Fixes #28 
Enhances ui of Signup page make it responsive and user Friendly ..
Before
beforeRegister
After Updation
registerTastyTrails

<!
### Required

- [ X] Filled out the "How to test" section in this PR
- [ X] Read Contributing guide
- [X ] Self-reviewed my own code
- [X ] Checked for warnings, there are none
- [ X] Removed all `console.logs`
- [ X] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 looks fine but still needs a better layout. Add some margin and padding,
Make the image big and in Circular shape.
Adjust font size they look too big.

The login card looks so small please maintain it's dimensions.
the signup card is still unaligned- the buttons
Also please update your PR

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique updated  ui 
updatedRegisterTastyTrails

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique  please see this as Signup page and tell me is all okay here and able to get merge ?

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 deployment is failing for this PR due to an error:
image

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique updated all part kindly check

**Comment by AlfiyaSiddique** [comment]
It is fine @sushil-sagar05, but both of your PR #307  and this have same changes so please close one of them

**Comment by sushil-sagar05** [comment]
> It is fine @sushil-sagar05, but both of your PR #307 and this have same changes so please close one of them

Hey @AlfiyaSiddique so for all that stuff i updated code of signup part and make it fully responsive please take a look
screenshots
updatedRegisterTastyTrails

https://github.com/user-attachments/assets/c1302967-4eaf-4298-96e1-b041e492e537

Thankyou consider this pr as ui changes of signup page

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 update your PR with the latest master branch, getting this bug on your PR which is already fixed and merged, means your branch is not updated. use git pull origin master and then push it.
image

Also, remove **image-login.jpg** & **newFoodSignup.jpeg** images as they are unused. I will merge it and then

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique it is saying already uptodate and displying that extra colon after footer

**Comment by AlfiyaSiddique** [comment]
Okay, @sushil-sagar05 can you check the footer component file and find the GogleTranslator component if it has a column beside it can you remove it?
If no comma is present just share the screenshot of code of that part

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique can i work on this after 2-3 days (on 29) due to my midsems.. Please don't close my this and #307 pr i have spent past 1 week on this issue and dont want to leave here.. Sorry for inconvenience.. Please wait 2-3 days

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique i also not deleted any single line from any component/pages this time 

> Okay, @sushil-sagar05 can you check the footer component file and find the GogleTranslator component if it has a column beside it can you remove it? If no comma is present just share the screenshot of code of that part

Hey @AlfiyaSiddique i don't change/delete this time a single line of code in components/pages except login or signup

**Review by dipexplorer — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
Hey @sushil-sagar05 do not worry, take your time :)

**Comment by sushil-sagar05** [comment]
hey @AlfiyaSiddique please review this

**Comment by AlfiyaSiddique** [comment]
Add some space above the text so that it does not look congested:
image

**Comment by AlfiyaSiddique** [comment]
And please remove unnecessary images I have told you this so many times. There are 3 new images and only 1 is used

**Comment by sushil-sagar05** [comment]
hey @AlfiyaSiddique i done almost all things as you said and i think this is all about so please review and then merge it

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 merge conflicts!  please fix

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique hey please see this asap

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 all looks good but your login change is not reflected in this pr:
image

Make sure you have updated your PR using git pull

**Comment by sushil-sagar05** [comment]
Hey @AlfiyaSiddique here it is showing already up to date..

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 can't see the image
image

Also, you may have made changes to the code while resolving conflicts:
Can you copy and paste the current login frontend code, including CSS so that we do not lose any contribution

**Comment by sushil-sagar05** [comment]
@AlfiyaSiddique updated as you said.. Review it

**Comment by AlfiyaSiddique** [comment]
@sushil-sagar05 a bit occupied will review it by Friday.

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
