### PR TITLE
✨ Dark mode Toggle added ✨ (issue #57 completed!)

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### the dark mode is added with lighter dark mode.

https://github.com/user-attachments/assets/06f10a3b-f8fe-407f-a881-3a2896b20a10

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@AlfiyaSiddique  its been 18hrs since i made this PR , please review this aswell,
Thank you!

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 the mentors of this project are not active, I have to handle all the PRs and issues. So please be patient

**Comment by AlfiyaSiddique** [comment]
Your PR will not be ignored and will be review, Don't worry

**Comment by T-Rahul-prabhu-38** [comment]
sure thank you

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 You still did not implemented the points I mention here: https://github.com/AlfiyaSiddique/TastyTrails/pull/67#issuecomment-2394176866

> @T-Rahul-prabhu-38
Also, the implemented dark mode is not looking good.
These are the issues with it:
The button is too simple - Add something like an icon of the sun and moon for light and dark mode
The black color is too dark and contrast use a relatively light black color
When you are making the background color black please plan according so that the recipe cards and other texts do not fades in which is the case currently
Please fix these

In the features section, the titles are still black and reduce readability.
the dark mode button is too simple.

**Comment by T-Rahul-prabhu-38** [comment]
ill fix it by tommorow,

**Comment by T-Rahul-prabhu-38** [comment]
@AlfiyaSiddique  I tried fixing it but its not working good due to clashes with other CSS codes, if possible can you please accept this PR.
Thank you

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 I can't accept the Pr like this as it does not add any value to the project.
Let me know if are you going to try again for this issue or should I close this PR and the issue as not planned.

**Comment by AlfiyaSiddique** [comment]
@T-Rahul-prabhu-38 will be closing this PR if find no activity by tomorrow

**Pull request closed without merging**
