### PR TITLE
Added Color to Navbar and Justified Texts

### PR DESCRIPTION
**Pull request by riddhij0804**
Issue number - #86 
**Added a color to the navbar and changed the font family of "Where Flavour meets Perfection" to make it visually appealing** 
navbar pink

**Justified these texts**
justify 1
justify 2
**Kindly assign appropriate labels and level.Thank you!**

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@riddhij0804 some improvements:
Remove the border-radius from navbar
When click on a nav bar item the font family changes please fix this, it is not needed to change the font
rest looks good to me

**Comment by riddhij0804** [comment]
Ok mam

**Comment by AlfiyaSiddique** [comment]
@riddhij0804  Can you make it a bit in the center: I have added the marks
image

**Comment by riddhij0804** [comment]
Mam, on my device its looking properly aligned.So I am not really able to make the changes.
 
aligned

**Comment by AlfiyaSiddique** [comment]
Okay, no issues, merging it

**Pull request merged**
