### PR TITLE
Made the navbar sticky.

### PR DESCRIPTION
**Pull request by vidhi-github**
## What does this PR do?

Makes the navbar sticky after first 100vh.

The handleScroll function now checks if window.scrollY (the scroll position) is greater than window.innerHeight, which represents 100vh.

When isSticky becomes true, the navbar will be fixed to the top with additional classes like bg-white and shadow-md.

Fixes # (issue)  

Issue No.: 269

## How should this be tested?

deployed the project on vercel.
I am facing the favicon issue ,, in my deployment...rest all is correct .. I have thoroughly checked my code.
I have made the navbar sticky.

I wanted to ask regarding this favicon issue how can I avoid it,, like it gives favicon error 404 error. Can u help me that plz.

- Test 1
- Test 2

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read Contributing guide
- [X] Self-reviewed my own code
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@vidhi-github it's not working, you can check the deploy preview. Please test

**Comment by AlfiyaSiddique** [comment]
@vidhi-github any updates?

**Comment by vidhi-github** [comment]
It's working only on first 100vh port height. U said to make the navbar sticky at first 100vh height. I did check it.

**Comment by AlfiyaSiddique** [comment]
@vidhi-github you have misunderstood I think
The requirement is as follows:
In the first 100vh, the navbar should not be sticky when scrolling:
After the first 100vh is scrolled (passed) the navbar should appear on top as sticked

As you can see in the picture the navbar does not appearing:
image

Please fix

**Comment by AlfiyaSiddique** [comment]
@vidhi-github any updates?

**Comment by vidhi-github** [comment]
Sorry Sir currently my exams r going on I would like to close this issue ...kindly do not merge this as the problem isn't solved.

Thanks alot for ur cooperation.

**Pull request closed without merging**
