### PR TITLE
Feat: added auto-labelling PR's

### LINKED ISSUE #279: ENHANCEMENT: Adding auto labelling to PR's
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

Adding gssoc-ext and hacktober fest ext lables automatically when raised a PR

### Component

auto-label.yml

### It should be implemented because

to auto add labels in PR, reduces manual task

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by sadath2001**
## What does this PR do?

This PR added auto-labelling for all the PR's once verified by adding gssoc-ext and hacktoberfest labels

Fixes #279 

Issues: 
image
PR's:
image

## How should this be tested?

- Test 1: Created a test issue to verify if my code change effects the issue labeling, figured that it does not.
- Test 2: Raised a PR to verify if the auto-labeling works as it intends to be, it works fine.

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read Contributing guide
- [X] Self-reviewed my own code
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by sadath2001** [comment]
auto-labelling build failed here since this PR doesnt have write permissions for this repo:
https://stackoverflow.com/questions/75995802/resource-not-accessible-by-integration-github-action-fails-for-pushed-commit

**Comment by AlfiyaSiddique** [comment]
@sadath2001 the permissions are read-write only still failing, check the second solution of the Stackoverflow link that you posted above. It mentions adding the permission in yml . Try that

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , fixed the error.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 can you make a test PR for this and share the image?

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique https://drive.google.com/file/d/1ZamNq5yRyKqw11oe3sSAnEg4AW3aQgh2/view?usp=sharing

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@sadath2001 is this PR good to merge or you have to add something?

**Comment by sadath2001** [comment]
Hi @AlfiyaSiddique , it's good to merge. Nothing to add. Just resolved the conflicts

**Comment by sadath2001** [comment]
Also, i thought that the WoB event was being merged with GSSOC ext and hence this event would be extended. Is that not so?

**Comment by AlfiyaSiddique** [comment]
It is not confirmed if this event will be extended or not, you can confirm with event managers on discord

**Comment by sadath2001** [comment]
ok thanks

**Pull request merged**
