### PR TITLE
 Fixed Recipe Image Storage & "Update Recipe" Page Improvements

### LINKED ISSUE #432: FEATURE: Store Recipe Images in the Database Instead of GitHub
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Description:**
Currently, recipe images are stored on GitHub and referenced by URLs. This approach can be inefficient and may lead to limitations such as bandwidth issues, dependency on GitHub's availability, and potential future scalability concerns. The goal is to store recipe images directly in the database, ensuring that all recipe data (including images) is contained within a centralized system.

### Component

backend

### It should be implemented because

Storing recipe images in the database, rather than on an external platform like GitHub, offers several advantages in terms of data management, scalability, security, and flexibility.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
### **Description**:

This PR addresses two major improvements for the recipe management functionality:

1. **Fixed Recipe Image Storage**: Updated the application to store recipe images directly in the database rather than storing them on GitHub, which improves data security, organization, and accessibility.
   
2. **Enhanced Update Recipe Page**: Added support for changing the recipe image on the update page, including backend support. Previously, there was no option to change the image, and the backend controller didn’t support this functionality.

---

### **Changes Made**:

1. **Recipe Image Storage Fix**:
   - **Before**: Recipe images were being stored on GitHub, which led to complications in managing image data and potential issues with scalability and access.
   - **After**: Recipe images are now stored directly in the recipes database, making it easier to retrieve, manage, and secure image data.
   - **Updates**:
     - Modified the backend image handling logic to store images in the database.
     - Adjusted API routes to support image storage as base64 or BLOB data.

2. **Update Recipe Page Fix**:
   - **Before**: The update recipe page did not allow users to change the recipe image, and there was no backend support to handle image updates.
   - **After**: Added a file input option for the recipe image on the update page, allowing users to upload a new image. Updated the backend controller to support image updates.
   - **Updates**:
     - Frontend: Added a file upload button on the update recipe page to allow changing the recipe image.
     - Backend: Enhanced the recipe update controller to handle changes in the image field, ensuring the new image is stored correctly in the database.
     - Updated validation and error handling to ensure the image change is optional but, if provided, stored correctly.

---

### **Screenshots/Visual Changes**:

https://github.com/user-attachments/assets/25016c1a-b962-4e4c-9854-449df45e7ad7

Screenshot 2024-11-09 at 12 04 51 AM

---

### **Related Issues**:

- Closes #432 

## How should this be tested?

- For storage shift from GitHub to mongoose db
    - You can either check you mongooses database or look into the schema change in recipe schema folder.

- For update fix
    - Go to update recipe page and press change image to upload new image
    - save the changes and refresh
    - changes will be present as its not in the database
    
## Checklist

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by IkkiOcean** [comment]
During the shifting of storage from GitHub to database, I found that update page is not able to change the image of the recipe. so I fixed it also! I hope you dont mind it.
@AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean  can you share a video by creating one dummy recipe with an image upload, since the current video only shows the update operation and not the add operation

**Comment by IkkiOcean** [comment]
> @IkkiOcean can you share a video by creating one dummy recipe with an image upload, since the current video only shows the update operation and not the add operation

yeah sure! doing it right away

**Comment by AlfiyaSiddique** [comment]
Also remove the GitHub related envs from the env example file

**Comment by IkkiOcean** [comment]
https://github.com/user-attachments/assets/ca8efe8f-76bc-4c6b-a6e8-3be871db953a
@AlfiyaSiddique the video of upload

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
