### PR TITLE
Added Resend Email Verification and Delete Unverified Users after 24 Hours

### LINKED ISSUE #430: FEATURE: Revamp Sign-Up Page with Verification Functionality
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Objective:**  
Revise and improve the current sign-up page to add essential features for better user experience, account security, and database integrity.

### Scope of Changes

1. **Enforce Email Verification Requirement:**  
   - Introduce a mandatory email verification step before account creation. Users must click a verification link sent to their email address to complete the registration process.

2. **Username Availability Check:**  
   - Implement real-time validation to check if the chosen username is already taken. Users will be informed immediately when a username is unavailable.

3. **Email Availability Check:**  
   - Implement real-time validation to check if the entered email address is already associated with an existing account. Users will be notified immediately if the email is already registered in the database.

### Component

/signup page

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by IkkiOcean**
This PR introduces two major features:
1. **Resend Email Verification**: Users who haven't verified their accounts can now request to resend the email verification link.
2. **Delete Unverified Users**: A scheduled task that deletes users who have not verified their account within 24 hours of registration.

#### Backend Changes:
1. **User Schema Update**:
   - A new field `timestamps` has been added to the user schema to track the timestamp of when the account was added.

2. **New Routes**:
   - A route has been added to allow users to request the resending of the email verification link.

3. **UserController Updates**:
   - Logic has been implemented in the `UserController` to handle the resending of verification emails, ensuring that the email is only resent after a 24-hour period has passed.
   - A scheduled task using a cron job has been added to delete unverified users who have not verified their account within 24 hours.

#### Frontend Changes:
1. **Resend Email Verification Page**:
   - A new page has been created on the frontend where users can request to resend the verification email if they have not received it or if the link has expired.
   
2. **Resend Button**:
   - A UI button has been added to trigger the request for the verification email to be resent.

### Summary of Changes:
1. **Backend**:
   - Updated the user schema to track the email resend timestamp.
   - Created routes for resending email verification links.
   - Implemented functionality for deleting unverified users after 24 hours.
   - Cron job added to automatically delete unverified users at midnight every day.

2. **Frontend**:
   - Added a page for users to request a new verification email.
   - Added functionality to handle user input and communicate with the backend to resend the email.

---

This PR aims to improve user experience by allowing users to request the resend of verification emails, and also ensures that unverified users are automatically cleaned up after 24 hours, enhancing overall system efficiency. Let me know if further changes or improvements are needed.

## How should this be tested?
 
 1) try signup and do no verify with the first email, instead click on the resend verification email button for new link
 2) during the start of backend, the terminal will log the start of deletion job

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### VIDEO and Screenshot
- reverify

https://github.com/user-attachments/assets/6b907188-acb3-4d81-8095-1e0058afda5c

- deletion of unverified user

Screenshot 2024-11-09 at 1 47 28 PM

- closes #430

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique please merge #435 before this to prevent any merge conflicts and this adds feature on that branch.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean please resolve conflicts

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique 
done :)

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean I have merged 435 before this still it has conflicts,
Can you please resolve

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique yes. I was actively removing them. it done now. you can merge

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
