### PR TITLE
added new changes to footer icons , effects

### PR DESCRIPTION
**Pull request by devxMani**
#56 done 

https://github.com/user-attachments/assets/34f13375-1cef-45f9-a9d0-4fb107e6ac0b

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@devxMani please update the PR

**Comment by devxMani** [comment]
@AlfiyaSiddique ??

**Comment by AlfiyaSiddique** [comment]
@devxMani, your PR has not been updated with the latest master branch, and there are conflicts.
image


Please find about the git pull command to update the PR.

**Comment by devxMani** [comment]
@AlfiyaSiddique so ill update with the new changes okk

**Comment by devxMani** [comment]
@AlfiyaSiddique i have created a new pr for this #230

**Pull request closed without merging**
