### PR TITLE
Loader at entry

### LINKED ISSUE #357: FEATURE: No response while registering
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

When user try to register and while backen process there is no response. At that time signup button should show it is processing otherwise user will feel page is giving no response especially when there is slow internet.

### Component

I would disable signup button while backen process and show that it is loading. Same i will do with login button

### It should be implemented because

It makes website interactive

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by raj-adi00**
## What does this PR do?
This PR adds loader when user clicks login and signup till backend processes and when result comes either error or success it is disabled

Now user can see loader till backend process. No new dependencies included
Fixes # (issue)
fixes #357 

Screenshot 2024-10-30 171644
No responsive issue
Screenshot 2024-10-30 171600
Loader looks something like this
## How should this be tested?

- Go to login Page and fill details and click login
- Go to signup page and fill details and click signup and you will see the change till processing occur
For better test you can ensure your network is slow so that you can properly see the effect as backend will take more time to process.
### Required

- [ x] Filled out the "How to test" section in this PR
- [x ] Read Contributing guide
- [ x] Self-reviewed my own code
- [x ] Checked for warnings, there are none
- [x ] Removed all `console.logs`
- [x ] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by raj-adi00** [comment]
https://github.com/user-attachments/assets/de509ee9-b057-4ac4-84ab-c1ad04a22750

**Comment by AlfiyaSiddique** [comment]
Yeah sounds good!

**Comment by raj-adi00** [comment]
https://github.com/user-attachments/assets/02e1e3dd-563f-42c2-ac18-470d88f569ad
Is it okay text is slightly bouncing

**Comment by AlfiyaSiddique** [comment]
yeah looks good, can you add some vector images above the text if you find any good ones, else let it be

**Comment by raj-adi00** [comment]
@AlfiyaSiddique  didn't find it. If you want to update just update Loader component. Please review and merge it

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
