### PR TITLE
Fix comment fetching in frontend

### LINKED ISSUE #389: BUG: Fetching recipe comments fails in backend
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Fetching recipe comments fails in backend

### Steps to reproduce

- Click on recipe card and see error in console.

### What was the expected result?

No error

### Proposed solution

Fix mongo query

p1

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Fix comment fetching in frontend

Fixes #389
Animation1

## How should this be tested?
- Go to recipe page -> See comments

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read Contributing guide
- [x] Self-reviewed my own code
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] The changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati doesn't seem to be fixed:

https://github.com/user-attachments/assets/a9edd28c-1a2b-4260-bff9-faa4c7054e42

The last comment does not fetch after refresh
Please check the deploy preview.
It might be a backend problem

**Comment by mehul-m-prajapati** [comment]
@AlfiyaSiddique : It works on local, don't know about prod.

https://github.com/user-attachments/assets/6aca7371-2c88-45b6-a821-f159bbfa2115

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
Nope not working the backend

**Comment by mehul-m-prajapati** [comment]
Okay let me raise another issue to fix it @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
okay removing the label from this PR and will add to that!
Since raising PR for same issue

**Pull request merged**
