### PR TITLE
Update Landing.jsx

### PR DESCRIPTION
**Pull request by neeru24**
This PR implements a hover effect for the hero text in the Hero component. The text changes color and scales up when hovered over, enhancing user interactivity and visual appeal. This change aims to improve the overall user experience by providing a dynamic response to user actions.

Thank you for considering this addition!

Kindly merge it :)

fixes: #94

### CODE REVIEW

**Comment by neeru24** [comment]
> This PR implements a hover effect for the hero text in the Hero component. The text changes color and scales up when hovered over, enhancing user interactivity and visual appeal. This change aims to improve the overall user experience by providing a dynamic response to user actions.
> 
> Thank you for considering this addition!
> 
> Kindly merge it :)
> 
> fixes: #94 

@AlfiyaSiddique check it please

**Comment by AlfiyaSiddique** [comment]
@ neeru24, please note that you have to get assigned to issues before opening any PR. The issue you tagged was not assigned yet and was under discussion. I asked for updates because there was no response on my question of design proposal.

**Comment by AlfiyaSiddique** [comment]
But no worries, I will review your changes and let you know it they are accepted or not.

**Comment by neeru24** [comment]
> @ neeru24, please note that you have to get assigned to issues before opening any PR. The issue you tagged was not assigned yet and was under discussion. I asked for updates because there was no response on my question of design proposal.

Oh sorry, My bad. I didn't notice that it's not assigned yet.

**Comment by AlfiyaSiddique** [comment]
@neeru24 since you have already raised the PR I will accept it but please note that from next time not to raise Prs until the issue is assigned to you. 
Also, some improvements are needed:
1. Do not change the color of text when applying animation.
2. Make a 3D text appearance when the text is hovered using CSS.
Please fix this, rest looks good.

**Comment by neeru24** [comment]
> @neeru24 since you have already raised the PR I will accept it but please note that from next time not to raise Prs until the issue is assigned to you. Also, some improvements are needed:
> 
> 1. Do not change the color of text when applying animation.
> 2. Make a 3D text appearance when the text is hovered using CSS.
>    Please fix this, rest looks good.

Okay, I'll do the changes

**Comment by neeru24** [comment]
> @neeru24 since you have already raised the PR I will accept it but please note that from next time not to raise Prs until the issue is assigned to you. Also, some improvements are needed:
> 
> 1. Do not change the color of text when applying animation.
> 2. Make a 3D text appearance when the text is hovered using CSS.
>    Please fix this, rest looks good.

Can you please check.

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by neeru24** [comment]
> @neeru24 since you have already raised the PR I will accept it but please note that from next time not to raise Prs until the issue is assigned to you. 
> Also, some improvements are needed:
> 1. Do not change the color of text when applying animation.
> 2. Make a 3D text appearance when the text is hovered using CSS.
> Please fix this, rest looks good.

Can you please add level 2?? I was new to this and it took more effort for redesigning according to you. 

Just a humble request. Rest as you say 😊

**Pull request merged**
