### PR TITLE
Fixed #13 : Scroll to top Component

### LINKED ISSUE #13: Implement Scroll-to-Top Button
I would like to enhance the user experience by adding a "Back to Top" button on the page. This button will allow users to easily navigate back to the top of the page

Please Assign me this feature @AlfiyaSiddique  with the tag "gssoc-ext" and "level"

### PR DESCRIPTION
**Pull request by samyak-aditya**
Fixed #13 
**Summary**:  
This pull request implements the `ScrollToTop` component to improve the visual design of the scroll-to-top button. 
This enhancements aim to improve user experience by making the scroll-to-top functionality more accessible and visually appealing.

Screenshot 2024-10-04 003332

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@samyak-aditya the bottom-to-up button is blocking the icons in the footer: Ex - The GitHub icon.
image

Can you fix this?
The rest looks good to me

**Comment by samyak-aditya** [comment]
Okay
I am fixing that

**Comment by samyak-aditya** [comment]
Hey @AlfiyaSiddique I have implemented some change to fix the issue you suggested above
Test it once and let me know if it works

**Comment by AlfiyaSiddique** [comment]
@netlify bot re-deploy preview

**Comment by AlfiyaSiddique** [comment]
No No, I am trying to redeploy your changes for a preview. Nothing to do from your side

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
