### PR TITLE
Feature pwa app

### PR DESCRIPTION
**Pull request by sadath2001**
hi @AlfiyaSiddique 

Issue: #110 

Kindly review

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@sadath2001 why are we adding those image files to the public folder is it necessary for caching?
Also, there are two files related to favicon, one is binary, also specify why this binary file needs to be pushed in this issue!

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , favico.ico isnt mandatory, it can be substituted to other favicons (.png) files if required.
Also, adding those images to public folder is necessary, since the manifest configured in vite config picks them up from public folder.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 If favicon is not mandatory than please remove all the three favicon files.

**Comment by sadath2001** [comment]
> @sadath2001 If favicon is not mandatory than please remove all the three favicon files.

Hi @AlfiyaSiddique , i meant only the one facivon.ico isnt mandatory, rest png file are required in order to show in the app.

**Comment by AlfiyaSiddique** [comment]
@sadath2001 Okay, then remove the one that is not mandatory and what about that binary file with favicon name, why is that file needed?

**Comment by sadath2001** [comment]
@AlfiyaSiddique i presume the binary files you are referring to are .png files? 
If not, could you send over a screenshot of the file you are referring to?

**Comment by AlfiyaSiddique** [comment]
image
@sadath2001

**Comment by sadath2001** [comment]
hi @AlfiyaSiddique , yes that can be deleted, ill delete it right away. (favicon.ico)
Rest all is required.

**Review by sadath2001 — COMMENTED** [review]
removed the binary

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
