### PR TITLE
[feat] : Added Multi-Lingual support to TastyTrails

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Description:
This PR introduces the Google Translate component to the Tasty Trails cooking recipe web application, allowing users to translate the site into multiple languages. Additionally, the color scheme of the Google Translate interface has been customized for a cleaner, consistent look.

- Closes : #193 

## Changes Made:
- **Added Google Translate Component:**
  - Implemented a `GoogleTranslate.jsx` component that integrates Google Translate, allowing users to select from various languages (English, Hindi, Urdu, etc.).
  - Ensured smooth script loading and proper handling of the Google Translate initialization.
  
- **Customized the Color Scheme:**
  - Updated the background, borders, text, and hover styles in the Google Translate component to use white and red.
  - Applied the new colors to the dropdown, borders, and text to ensure a cohesive design.
  - Maintained all transitions and hover effects with the updated colors.

## Video: 

https://github.com/user-attachments/assets/65b18d2d-e17a-43d7-841c-def0aee075a3

**Languages Supported:**
- English, Hindi, Spanish, Punjabi, Sanskrit, Marathi, Urdu, Bengali, Japanese, Korean, Chinese, Dutch, French, German, Italian, Tamil, Telugu, and more.

**Files Modified:**
- `GoogleTranslate.jsx`
- `Footer.jsx`

**Testing:**
- Tested the Google Translate functionality to ensure the site translates correctly into the supported languages.
- Verified the new color scheme is applied consistently across all devices and screen sizes.
- Checked for performance impacts to ensure the script loads efficiently without affecting page performance.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Please provide level 3 as it is a very crucial feature.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean please update the PR

**Comment by AlfiyaSiddique** [comment]
@IkkiO due to some syntax error the build is breaking:
Diagnosis:

> The build failure is due to errors in the HTML structure in the file [Footer.jsx](https://github.com/AlfiyaSiddique/TastyTrails/blob/multilingual-support/frontend/src/Components/Footer.jsx). Specifically, it shows a mix-up of opening and closing tags (div, span, footer), and an expected parentheses error.
Solution
To resolve the build failure:
In [Footer.jsx](https://github.com/AlfiyaSiddique/TastyTrails/blob/multilingual-support/frontend/src/Components/Footer.jsx):
Correct the mixed up opening and closing tags to ensure proper nesting and matching of elements.
Fix the expected parentheses error by ensuring proper syntax in the specified line numbers.
After making these corrections, commit your changes, push them to the repository, and trigger a new build to confirm the issue is resolved.

the above is the diagnosis please fix it

**Comment by IkkiOcean** [comment]
@AlfiyaSiddique did the changes. sorry I left a closing div there without a opening one.

**Comment by AlfiyaSiddique** [comment]
@IkkiOcean the functionality works perfectly fine just one last change:

In your branch, there is more space above the navbar. Also, the language button is not adjusted properly. Make it more small and add a margin so it does not look out of frame.
image

Actual:
image

**Comment by IkkiOcean** [comment]
is this okay now? removed the extra space in navbar and added some padding , margin in the element

Screenshot 2024-10-14 at 10 40 04 PM

**Comment by AlfiyaSiddique** [comment]
Looks great @IkkiOcean 
Thanks for the contribution

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
